# Edit this Gemfile to bundle your application's dependencies.
source 'http://rubygems.org'

gem "rails", '3.0.9'

gem 'mysql2', "~> 0.2.0"
gem 'haml'
gem 'mime-types', :require => 'mime/types'
gem 'radius', '0.7.0.prerelease'
gem 'RedCloth', :require => 'redcloth'
# gem 'BlueCloth', :require => 'bluecloth'
gem 'gruff'
# gem 'slave'
gem 'hpricot'
gem 'daemons'
gem 'maruku'
gem 'net-ssh', :require => 'net/ssh'
gem 'rmagick', :require => 'RMagick'
gem 'libxml-ruby', :require => 'xml'
# gem 'soap4r', :require => 'soap/soap'
# gem 'SystemTimer', :require => 'system_timer'
gem 'memcache-client', :require => 'memcache'
gem 'resthome'
gem "nokogiri"
gem 'image_size'

# Workling gems
gem 'eventmachine'
gem 'starling'

group :test, :spec, :cucumber, :selenium do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'jquery-rails'
  gem 'rails_code_qa'
  gem 'hpricot'
  gem 'fakeweb'
  gem 'ZenTest'
  gem 'rspec_tag_matchers'
end

group :development, :test do
  gem 'rails-dev-boost', :git => 'git://github.com/thedarkone/rails-dev-boost.git', :require => 'rails_development_boost'
end

group :selenium do
#  gem 'selenium-client',   '1.2.18'
end
