# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "client_users", :force => true do |t|
    t.column "client_id",       :integer,               :default => 0,  :null => false
    t.column "username",        :string,                :default => "", :null => false
    t.column "hashed_password", :string,  :limit => 64, :default => "", :null => false
    t.column "client_admin",    :boolean
    t.column "system_admin",    :boolean
    t.column "email",           :string,                :default => ""
    t.column "options",         :text
  end

  create_table "clients", :force => true do |t|
    t.column "name",         :string,  :limit => 100, :default => "", :null => false
    t.column "domain_limit", :integer,                :default => 1,  :null => false
  end

  create_table "domain_modules", :force => true do |t|
    t.column "name",      :string
    t.column "domain_id", :integer
    t.column "access",    :string
  end

  create_table "domains", :force => true do |t|
    t.column "name",        :string,  :default => "",             :null => false
    t.column "database",    :string,  :default => "",             :null => false
    t.column "client_id",   :integer, :default => 0,              :null => false
    t.column "status",      :string,  :default => "initializing"
    t.column "domain_type", :string,  :default => "domain"
    t.column "redirect",    :string
    t.column "file_store",  :integer
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code",                   :string, :limit => 2
    t.column "english_name",           :string
    t.column "date_format",            :string
    t.column "currency_format",        :string
    t.column "currency_code",          :string, :limit => 3
    t.column "thousands_sep",          :string, :limit => 2
    t.column "decimal_sep",            :string, :limit => 2
    t.column "currency_decimal_sep",   :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "index_globalize_countries_on_code"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1",             :string,  :limit => 2
    t.column "iso_639_2",             :string,  :limit => 3
    t.column "iso_639_3",             :string,  :limit => 3
    t.column "rfc_3066",              :string
    t.column "english_name",          :string
    t.column "english_name_locale",   :string
    t.column "english_name_modifier", :string
    t.column "native_name",           :string
    t.column "native_name_locale",    :string
    t.column "native_name_modifier",  :string
    t.column "macro_language",        :boolean
    t.column "direction",             :string
    t.column "pluralization",         :string
    t.column "scope",                 :string,  :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "index_globalize_languages_on_iso_639_1"
  add_index "globalize_languages", ["iso_639_2"], :name => "index_globalize_languages_on_iso_639_2"
  add_index "globalize_languages", ["iso_639_3"], :name => "index_globalize_languages_on_iso_639_3"
  add_index "globalize_languages", ["rfc_3066"], :name => "index_globalize_languages_on_rfc_3066"

  create_table "globalize_translations", :force => true do |t|
    t.column "type",                :string
    t.column "tr_key",              :string
    t.column "table_name",          :string
    t.column "item_id",             :integer
    t.column "facet",               :string
    t.column "language_id",         :integer
    t.column "pluralization_index", :integer
    t.column "text",                :text
    t.column "built_in",            :boolean, :default => false
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "globalize_translations_tr_key_index"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_index"

  create_table "system_issue_notes", :force => true do |t|
    t.column "system_issue_id",   :integer
    t.column "entered_at",        :datetime
    t.column "work_time",         :decimal,  :precision => 5, :scale => 2, :default => 0.0
    t.column "action",            :string
    t.column "domain_file_id",    :integer
    t.column "note",              :text
    t.column "entered_user_type", :string
    t.column "entered_user_id",   :integer
  end

  add_index "system_issue_notes", ["system_issue_id", "entered_at"], :name => "problem_entered_on"

  create_table "system_issues", :force => true do |t|
    t.column "reported_at",          :datetime
    t.column "reporting_domain",     :string
    t.column "reporter_user_type",   :string
    t.column "reporter_user_id",     :integer
    t.column "reported_type",        :string,                                 :default => "auto"
    t.column "status",               :string,                                 :default => "reported"
    t.column "estimate",             :decimal,  :precision => 5, :scale => 2, :default => 0.0
    t.column "time_log",             :decimal,  :precision => 5, :scale => 2, :default => 0.0
    t.column "completed_percentage", :integer,                                :default => 0
    t.column "updated_at",           :datetime
    t.column "reproducible",         :boolean,                                :default => false
    t.column "location",             :string
    t.column "behavior",             :text
    t.column "expected_behavior",    :text
  end

  add_index "system_issues", ["reporting_domain", "location", "reported_at"], :name => "dmn_loc_rep_index"

end
